// Code generated by "stringer -type=PacketType"; DO NOT EDIT.

package rcon

import "strconv"

const (
	_PacketType_name_0 = "typeErrortypeResponse"
	_PacketType_name_1 = "typeCommandtypeLogin"
)

var (
	_PacketType_index_0 = [...]uint8{0, 9, 21}
	_PacketType_index_1 = [...]uint8{0, 11, 20}
)

func (i PacketType) String() string {
	switch {
	case -1 <= i && i <= 0:
		i -= -1
		return _PacketType_name_0[_PacketType_index_0[i]:_PacketType_index_0[i+1]]
	case 2 <= i && i <= 3:
		i -= 2
		return _PacketType_name_1[_PacketType_index_1[i]:_PacketType_index_1[i+1]]
	default:
		return "PacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
